modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="blood_crystal"
version="1.0.0"
displayName="Blood crystal"
credits="Code by SuperFeda, texture by Hothili."
displayURL="https://discord.gg/GFpmfNPPPy"
authors="FedaProduction"

[[dependencies.blood_crystal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.blood_crystal]]
    modId="enhancedcelestials"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


